$(document).ready(() => {
  $("#scroll-button").click(() => {
    $("html, body").animate(
      {
        scrollTop: $("#about-section").offset().top,
      },
      800
    );
  });

  $(".current-year").html(new Date().getFullYear());

  $("#input-tel-main, #input-tel-contacts").mask("(000) 000-0000");

  const checkForm = (form) => {
    const patternEmail = /^[^ ]+@[^ ]+\.[a-z]{2,4}$/;
    const isValidInputs = [];

    form.find(":input[type!=submit]").each(function () {
      const value = $(this).val().trim();
      let isValidInput = true;
      const isRequired = $(this).prop("required");

      if (isRequired) {
        isValidInput = !!value;
      }
      if ($(this).attr("type") === "email") {
        isValidInput = patternEmail.test(value);
      }

      if (isValidInput) {
        $(this).removeClass("border-red-500");
      } else {
        $(this).addClass("border-red-500");
      }

      isValidInputs.push(isValidInput);
    });

    return isValidInputs.every((el) => el);
  };

  const setResponseMessage = (status) => {
    const el = $("#response-message");

    if (status === "success") {
      el.removeClass("text-red-500")
        .addClass("text-blue-dark")
        .html("Email was sent successfully");
    } else {
      el.removeClass("text-blue-dark")
        .addClass("text-red-500")
        .html("Oops... Something went wrong!");
    }

    el.fadeIn(500, () => {
      setTimeout(() => {
        el.fadeOut(500);
      }, 3000);
    });
  };

  $("form").on("submit", function (e) {
    e.preventDefault();

    grecaptcha
      .execute("6Ld7bTgpAAAAAFlJzGkSK2YlG_Vpk0LcyZ-5AcFo", { action: "submit" })
      .then(function (token) {
        $("#g-recaptcha-response").val(token);

        const data = {};
        const isValid = checkForm($("form"));
        const formData = $("form").serializeArray();

        $.each(formData, function () {
          data[this.name] = this.value;
        });

        if (isValid) {
          $.ajaxSetup({
            headers: {
              "X-Requested-With": "XMLHttpRequest",
            },
            xhrFields: {
              withCredentials: true,
            },
          });
          $.post("https://api.magendamd.com/api/v1/contact-message", data)
            .done((data, status) => {
              setResponseMessage(status);
              $("form")[0].reset();
            })
            .fail((data, status) => {
              console.log(data);
              setResponseMessage(status);
            });
        }
      });
  });

  const swiper = new Swiper(".swiper", {
    direction: "horizontal",
    slidesPerView: 3.5,
    slidesPerGroup: 3,
    spaceBetween: 25,
    grabCursor: true,
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
      renderBullet: (index, className) => {
        return `<span class=${className}>${index < 9 ? "0" : ""}${
          index + 1
        }</span>`;
      },
      dynamicBullets: true,
      dynamicMainBullets: 10,
    },
    breakpoints: {
      320: {
        slidesPerView: 2.5,
        slidesPerGroup: 2,
      },
      1280: {
        slidesPerView: 3.5,
        slidesPerGroup: 3,
      },
      1536: {
        spaceBetween: 50,
      },
    },
  });

  const getTestimonials = () => {
    const users = [
      {
        rating: "5.0",
        date: "11/08/24",
        text: "The reminders and EHR in Magenda keep our internal medicine practice organized. The billing tools are straightforward and efficient.",
        image: "/public/images/users/202.jpg",
        name: "Danielle O.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "11/05/24",
        text: "Our chiropractic office relies on Magenda’s reminders and billing tools. The clock-in feature is great for tracking hours.",
        image: "/public/images/users/201.jpg",
        name: "Rachel M.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "11/02/24",
        text: "The EHR in Magenda are perfect for physical therapy. The billing tools are efficient, and clock-in is a useful feature.",
        image: "/public/images/users/200.jpg",
        name: "Hazel F.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "10/28/24",
        text: "Our office loves Magenda’s user-friendly design. The reminders, billing, and clock-in feature keep everything organized.",
        image: "/public/images/users/199.jpg",
        name: "Rita S.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "10/27/24",
        text: "Magenda’s organized reminders and clock-in feature are perfect for our surgery center. The billing tools are also reliable.",
        image: "/public/images/users/198.jpg",
        name: "Megan B.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "10/25/24",
        text: "The reminders and intuitive EHR in Magenda are great for physical therapy. The billing tools are easy to use, and clock-in is helpful.",
        image: "/public/images/users/197.jpg",
        name: "Lillian K.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "10/21/24",
        text: "Our chiropractic office finds Magenda’s reminders and billing tools perfect for our needs. The clock-in feature is an added bonus.",
        image: "/public/images/users/196.jpg",
        name: "Dr. Andrew G.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "10/15/24",
        text: "Scheduling and reminders in Magenda are simple and efficient. The billing and clock-in features keep everything running smoothly.",
        image: "/public/images/users/195.jpg",
        name: "Diego S.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "10/09/24",
        text: "The reminders and billing in Magenda make it easy to manage our surgery center. The clock-in feature is very helpful too.",
        image: "/public/images/users/194.jpg",
        name: "Ruby G.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "09/27/24",
        text: "Our physical therapy team loves the organized reminders and EHR in Magenda. The clock-in feature is a great addition.",
        image: "/public/images/users/193.jpg",
        name: "Dr. Sam Y.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "09/20/24",
        text: "Magenda’s reminders, tasks, and intuitive design are ideal for a busy chiropractic office. The billing tools are also straightforward.",
        image: "/public/images/users/192.jpg",
        name: "Bertha S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "09/02/24",
        text: "The reminders and billing in Magenda keep our office running smoothly. The clock-in feature is perfect for tracking hours.",
        image: "/public/images/users/191.jpg",
        name: "Cheryl P.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "08/15/24",
        text: "Magenda’s user-friendly reminders and organized design keep our internal medicine practice running smoothly. Billing is also easy to manage.",
        image: "/public/images/users/190.jpg",
        name: "Anna B.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "08/12/24",
        text: "Our physical therapy office couldn’t be happier with Magenda. The reminders, billing, and clock-in feature make our day easier.",
        image: "/public/images/users/189.jpg",
        name: "Paula H.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "07/21/24",
        text: "The reminders, clock-in feature, and intuitive EHR in Magenda are perfect for our surgery center. Everything is so organized.",
        image: "/public/images/users/188.jpg",
        name: "Shannon C.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "07/13/24",
        text: "Magenda’s organized reminders and tasks make it ideal for a busy chiropractic office. The billing tools are also very efficient.",
        image: "/public/images/users/187.jpg",
        name: "Jason B.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "07/12/24",
        text: "Our office runs smoother with Magenda. The reminders, billing, and clock-in feature keep us on track every day.",
        image: "/public/images/users/186.jpg",
        name: "Cheryl T.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "07/12/24",
        text: "The reminders and EHR in Magenda are fantastic for physical therapy. The billing tools are easy to use, and clock-in is helpful.",
        image: "/public/images/users/185.jpg",
        name: "Dr. Mohamed S.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "07/06/24",
        text: "Magenda’s user-friendly reminders and scheduling make managing our office easy. The billing and collections tools are also excellent.",
        image: "/public/images/users/184.jpg",
        name: "Sara D.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "06/11/24",
        text: "Our chiropractic team loves Magenda’s organized layout. The reminders, billing, and clock-in feature make everything so efficient.",
        image: "/public/images/users/183.jpg",
        name: "Mildred A.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "06/01/24",
        text: "The reminders, tasks, and clock-in feature in Magenda are ideal for our physical therapy office. It keeps everything organized daily.",
        image: "/public/images/users/182.jpg",
        name: "Brian L.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "05/25/24",
        text: "The intuitive EHR in Magenda has transformed our internal medicine practice. The reminders and billing tools make everything easy to manage.",
        image: "/public/images/users/181.jpg",
        name: "Samuel O.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "05/22/24",
        text: "Magenda’s reminders and billing tools make it easy to manage our chiropractic office. The clock-in feature is great for tracking staff hours.",
        image: "/public/images/users/180.jpg",
        name: "Wanda O.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "05/20/24",
        text: "Scheduling and reminders in Magenda are user-friendly and organized. The billing tools are efficient, and the clock-in feature is a great addition.",
        image: "/public/images/users/179.jpg",
        name: "Dr. Alex S.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "05/11/24",
        text: "The reminders, clock-in feature, and billing tools in Magenda keep our physical therapy office running smoothly every day.",
        image: "/public/images/users/178.jpg",
        name: "Julie L.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "05/07/24",
        text: "Magenda’s EHR is excellent for internal medicine. The reminders and tasks keep us on track, and billing is easy to manage.",
        image: "/public/images/users/177.jpg",
        name: "Marilyn S.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "05/06/24",
        text: "Our chiropractic office loves Magenda’s intuitive design. The reminders, billing, and clock-in feature keep everything organized.",
        image: "/public/images/users/176.jpg",
        name: "Dr. Sam P.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "04/20/24",
        text: "The reminders, scheduling, and billing tools in Magenda are fantastic for a busy surgery center. The clock-in feature is a real time-saver.",
        image: "/public/images/users/175.jpg",
        name: "Alice P.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "04/17/24",
        text: "Magenda’s EHR is great for tracking patient care. The reminders and clock-in features make managing our physical therapy office so much easier.",
        image: "/public/images/users/174.jpg",
        name: "Helen F.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "04/10/24",
        text: "The organized reminders and EHR in Magenda are perfect for our chiropractic office. Billing is straightforward, and the clock-in feature helps manage hours.",
        image: "/public/images/users/173.jpg",
        name: "Janet J.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "03/17/24",
        text: "Our medical office runs efficiently with Magenda. The reminders, clock-in feature, and billing tools make everything so simple to use.",
        image: "/public/images/users/172.jpg",
        name: "Dr. Kevin B.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "03/14/24",
        text: "Magenda has everything our physical therapy office needs! The reminders, tasks, and clock-in feature keep us organized every day.",
        image: "/public/images/users/171.jpg",
        name: "Dorothy T.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "03/10/24",
        text: "The reminders and intuitive EHR make Magenda a standout for our surgery center. Billing and collections are easier to manage as well.",
        image: "/public/images/users/170.jpg",
        name: "Dr. Rebecca R.",
        speciality: "Surgeon",
      },
      {
        rating: "5.0",
        date: "03/05/24",
        text: "Scheduling and reminders in Magenda keep our chiropractic office on track. The EHR is efficient, and the clock-in feature is helpful for tracking hours.",
        image: "/public/images/users/169.jpg",
        name: "Scott S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "03/02/24",
        text: "Magenda’s reminders, billing, and clock-in feature are amazing for our internal medicine practice. The software is organized and easy for our team.",
        image: "/public/images/users/168.jpg",
        name: "Stephanie D.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "02/25/24",
        text: "We love Magenda’s organized design! The reminders, scheduling, and clock-in feature help our surgery center run efficiently, and the billing is straightforward.",
        image: "/public/images/users/167.jpg",
        name: "Nancy Y.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "02/18/24",
        text: "The intuitive EHR in Magenda makes it a great fit for physical therapy offices. The reminders and billing tools are also incredibly user-friendly.",
        image: "/public/images/users/166.jpg",
        name: "Dr. Brian M.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "02/15/24",
        text: "Magenda’s task management and reminders keep us running smoothly. The billing tools are fantastic, and the clock-in feature is a great addition.",
        image: "/public/images/users/165.jpg",
        name: "Melissa W.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "02/13/24",
        text: "The user-friendly EHR and reminders in Magenda have transformed our office. Scheduling is smooth, and the clock-in feature is great for managing staff hours.",
        image: "/public/images/users/164.jpg",
        name: "Brooke P.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "02/10/24",
        text: "Magenda has simplified our chiropractic office’s workflow. The organized reminders, billing, and clock-in feature make it easy to stay on top of everything.",
        image: "/public/images/users/163.jpg",
        name: "Dr. Laura G.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "02/08/24",
        text: "Our physical therapy office appreciates the user-friendly reminders and billing tools in Magenda. The EHR is organized and easy to navigate.",
        image: "/public/images/users/162.jpg",
        name: "Susan D.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "02/06/24",
        text: "The reminders, clock-in, and intuitive design make Magenda perfect for our surgery center. Billing and collections are excellent too.",
        image: "/public/images/users/161.jpg",
        name: "Dr. Michael T.",
        speciality: "Surgeon",
      },
      {
        rating: "4.5",
        date: "02/05/24",
        text: "Our office couldn’t function as smoothly without Magenda. The organized reminders, scheduling, and billing tools keep us on track daily.",
        image: "/public/images/users/160.jpg",
        name: "Mary A.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "01/28/24",
        text: "The EHR in Magenda is ideal for physical therapy. The reminders and task features are easy to use, and billing is efficient.",
        image: "/public/images/users/159.jpg",
        name: "Brenda M.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "01/26/24",
        text: "Magenda’s intuitive reminders and billing make it a great choice for any medical office. The clock-in feature is very useful for managing hours.",
        image: "/public/images/users/158.jpg",
        name: "Sebastian P.",
        speciality: "Coding specialists",
      },
      {
        rating: "5.0",
        date: "01/19/24",
        text: "Magenda’s EHR and reminders make our physical therapy office efficient. The user-friendly design is easy for everyone to use.",
        image: "/public/images/users/157.jpg",
        name: "Marian O.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "01/15/24",
        text: "Our surgery center loves Magenda. The reminders, scheduling, and billing make everything easy to manage, and the clock-in feature is great.",
        image: "/public/images/users/156.jpg",
        name: "Sarah L.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "01/12/24",
        text: "The reminders, tasks, and organized design of Magenda make it perfect for a busy medical office. The billing tools are reliable too.",
        image: "/public/images/users/155.jpg",
        name: "Tara M.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "01/10/24",
        text: "Magenda’s intuitive EHR and reminders are excellent for physical therapy. The billing tools are efficient and easy to navigate.",
        image: "/public/images/users/154.jpg",
        name: "Becky F.",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "12/23/23",
        text: "Scheduling and reminders in Magenda are very user-friendly. The clock-in feature and billing tools keep our chiropractic office on track.",
        image: "/public/images/users/153.jpg",
        name: "Glenda S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "12/22/23",
        text: "The reminders, task features, and billing in Magenda are perfect for our office. The clock-in feature is a great addition too!",
        image: "/public/images/users/152.jpg",
        name: "Dr. Robert P.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "12/19/23",
        text: "Magenda’s EHR is fantastic for our surgery center. The reminders, scheduling, and billing tools make it simple to manage our day.",
        image: "/public/images/users/151.jpg",
        name: "Ben K.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "12/18/23",
        text: "The reminders and task integration in Magenda keep us organized, and the clock-in feature is great for tracking hours.",
        image: "/public/images/users/150.jpg",
        name: "Courtney S.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "12/16/23",
        text: "Scheduling, reminders, and billing in Magenda are easy to use. The clock-in feature helps us track our chiropractic team’s hours.",
        image: "/public/images/users/149.jpg",
        name: "Caroline Y.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "12/15/23",
        text: "The organized reminders, tasks, and clock-in feature make Magenda a great choice for our busy surgery center.",
        image: "/public/images/users/148.jpg",
        name: "Tonya J.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "12/11/23",
        text: "Magenda’s user-friendly interface and reminders make scheduling simple. The billing tools are straightforward and efficient, perfect for our internal medicine office.",
        image: "/public/images/users/147.jpg",
        name: "Lucy M.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "12/08/23",
        text: "Our physical therapy office couldn’t be happier with Magenda. The reminders, EHR, and clock-in feature make it simple to stay organized.",
        image: "/public/images/users/146.jpg",
        name: "Jo L.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "12/08/23",
        text: "The reminders and billing are efficient in Magenda. Scheduling and clock-in features are easy to manage, and the interface is intuitive.",
        image: "/public/images/users/145.jpg",
        name: "Dr. Steven R.",
        speciality: "Internal Medicine",
      },
      {
        rating: "4.5",
        date: "12/06/23",
        text: "The reminders and organized EHR in Magenda are perfect for our surgery center. Billing and task features make managing our office easier.",
        image: "/public/images/users/144.jpg",
        name: "Carlos P.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "12/05/23",
        text: "Our chiropractic office loves Magenda’s user-friendly design. Scheduling, reminders, and billing are simple, and the clock-in feature is fantastic.",
        image: "/public/images/users/143.jpg",
        name: "Violet T.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "12/01/23",
        text: "Magenda’s EHR is well-suited for physical therapy. The reminders, tasks, and billing tools keep us organized every day.",
        image: "/public/images/users/142.jpg",
        name: "Dora C.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "11/26/23",
        text: "The intuitive design, reminders, and task features in Magenda make our surgery center organized. The billing and EHR tools are fantastic.",
        image: "/public/images/users/141.jpg",
        name: "Vickie S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "11/24/23",
        text: "The clock-in feature is great for our chiropractic team. Scheduling, reminders, and billing have all become simpler with Magenda.",
        image: "/public/images/users/140.jpg",
        name: "Ella N.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "11/24/23",
        text: "The reminders, tasks, and beautiful layout of Magenda are perfect for our busy office. The billing tools are user-friendly and efficient.",
        image: "/public/images/users/139.jpg",
        name: "Ross G.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "11/22/23",
        text: "Our surgery center relies on Magenda. The organized scheduling, reminders, and billing are simple to use, and the clock-in feature is a bonus.",
        image: "/public/images/users/138.jpg",
        name: "Gina O.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "11/09/23",
        text: "Magenda’s intuitive EHR and reminders make scheduling patient appointments easy. The clock-in feature is great for tracking our team’s hours.",
        image: "/public/images/users/137.jpg",
        name: "Dr. Linda H.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "11/05/23",
        text: "Our physical therapy office appreciates the clock-in feature for managing hours. Magenda’s reminders and tasks keep us organized daily.",
        image: "/public/images/users/136.jpg",
        name: "Christy P.",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "10/25/23",
        text: "The organized reminders and beautiful interface make Magenda a favorite in our chiropractic practice. Billing and collections are straightforward too.",
        image: "/public/images/users/135.jpg",
        name: "Mae K.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "10/21/23",
        text: "Magenda is perfect for busy offices. The scheduling, reminders, and billing are very efficient, and the clock-in feature is helpful for tracking hours.",
        image: "/public/images/users/134.jpg",
        name: "Barbara N.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "10/17/23",
        text: "Our chiropractic office runs smoother with Magenda. The reminders and intuitive EHR make patient management easy, while billing is straightforward.",
        image: "/public/images/users/133.jpg",
        name: "Virginia T.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "10/15/23",
        text: "Magenda’s reminders, scheduling, and task integration make our office run smoothly. The EHR is so organized and easy for our team to use.",
        image: "/public/images/users/132.jpg",
        name: "Rebecca N.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "10/12/23",
        text: "The intuitive design and clock-in feature are fantastic for our surgery center. Magenda keeps our team organized and efficient.",
        image: "/public/images/users/131.jpg",
        name: "Christina R.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "10/11/23",
        text: "Scheduling, reminders, and billing are a breeze with Magenda. The task integration is essential to our busy chiropractic practice.",
        image: "/public/images/users/130.jpg",
        name: "Irene S.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "10/06/23",
        text: "Magenda’s reminders and EHR make our physical therapy office more organized. The user-friendly design is perfect for our team!",
        image: "/public/images/users/129.jpg",
        name: "Lucas M.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "10/02/23",
        text: "The clock-in feature is perfect for tracking hours. Magenda’s scheduling, reminders, and billing tools make it easy to manage a busy practice.",
        image: "/public/images/users/128.jpg",
        name: "Sandra D.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "09/27/23",
        text: "Our physical therapy office couldn’t function as smoothly without Magenda. The EHR and reminders make managing patient care easy.",
        image: "/public/images/users/127.jpg",
        name: "Dr. Jack P.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "09/23/23",
        text: "The reminders, billing, and organized interface make Magenda ideal for our surgery center. The clock-in feature is a great addition!",
        image: "/public/images/users/126.jpg",
        name: "Ann O.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "09/20/23",
        text: "Our chiropractic team loves the intuitive scheduling and billing in Magenda. The reminders are a huge help for patient care.",
        image: "/public/images/users/125.jpg",
        name: "Karen B.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "09/13/23",
        text: "The EHR is fantastic for our physical therapy office. The reminders and clock-in feature keep us running smoothly every day.",
        image: "/public/images/users/124.jpg",
        name: "Carol S.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "09/11/23",
        text: "Magenda’s reminders and task features are ideal for our surgery center. The billing and collections tools are efficient and easy to use.",
        image: "/public/images/users/123.jpg",
        name: "Dr. Liam M.",
        speciality: "Surgeon",
      },
      {
        rating: "4.5",
        date: "09/10/23",
        text: "The clock-in feature is a valuable addition for our team. Magenda’s scheduling, reminders, and billing tools keep us organized.",
        image: "/public/images/users/122.jpg",
        name: "Tom T.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "09/07/23",
        text: "Magenda’s intuitive EHR is great for physical therapy. The reminders and tasks ensure we stay on track and meet patient needs.",
        image: "/public/images/users/121.jpg",
        name: "Diane S.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "09/04/23",
        text: "The billing tools in Magenda are fantastic. The reminders and clock-in feature make it easy to manage our chiropractic team.",
        image: "/public/images/users/120.jpg",
        name: "Samuel S.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "08/27/23",
        text: "Our team loves Magenda. The reminders, EHR, and organized interface make it the perfect tool for a busy medical office.",
        image: "/public/images/users/119.jpg",
        name: "Gloria P.",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "08/22/23",
        text: "Magenda’s reminders and billing are amazing! The user-friendly interface and task integration keep our surgery center on track.",
        image: "/public/images/users/118.jpg",
        name: "Dr. Anthony V.",
        speciality: "Surgeon",
      },
      {
        rating: "5.0",
        date: "08/20/23",
        text: "The clock-in feature is perfect for managing hours. The scheduling and reminders keep our physical therapy office organized daily.",
        image: "/public/images/users/117.jpg",
        name: "Heather P.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "08/16/23",
        text: "The user-friendly design and scheduling in Magenda make it a must-have. Reminders and tasks help keep everything organized.",
        image: "/public/images/users/116.jpg",
        name: "Cheryl C.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "08/15/23",
        text: "Our chiropractic office appreciates the intuitive EHR and reminders in Magenda. The organized design makes scheduling and billing effortless.",
        image: "/public/images/users/115.jpg",
        name: "Karen M.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "08/12/23",
        text: "The reminders, clock-in, and billing features in Magenda have made our office more efficient than ever. Highly recommend for busy medical practices.",
        image: "/public/images/users/114.jpg",
        name: "Dr. David B.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "08/07/23",
        text: "Magenda’s EHR is perfect for physical therapy. The reminders, tasks, and billing tools keep everything running smoothly!",
        image: "/public/images/users/113.jpg",
        name: "Melissa K.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "08/05/23",
        text: "The intuitive design and reminders in Magenda are ideal for our surgery center. The billing tools are efficient and easy to use.",
        image: "/public/images/users/112.jpg",
        name: "Julia S.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "08/03/23",
        text: "Our chiropractic office couldn’t be happier with Magenda. The task integration and reminders keep us organized, and the clock-in feature is a great bonus.",
        image: "/public/images/users/111.jpg",
        name: "Theodore R.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "08/02/23",
        text: "The EHR is fantastic for our physical therapy office. Magenda’s reminders, billing tools, and easy interface make it an essential tool.",
        image: "/public/images/users/110.jpg",
        name: "Mildred P.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "07/28/23",
        text: "The clock-in feature helps us track staff hours, and the reminders keep us on schedule. Magenda is perfect for a busy medical office!",
        image: "/public/images/users/109.jpg",
        name: "Annie O.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "07/25/23",
        text: "Magenda’s user-friendly interface has made our scheduling so much easier. The reminders and task feature are essential to our workflow.",
        image: "/public/images/users/108.jpg",
        name: "Angela S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "07/21/23",
        text: "Our office runs smoothly thanks to Magenda. The reminders, tasks, and organized EHR make it perfect for internal medicine.",
        image: "/public/images/users/107.jpg",
        name: "Dr. Lisa J.",
        speciality: "Internal Medicine",
      },
      {
        rating: "4.5",
        date: "07/20/23",
        text: "The clock-in feature is a game-changer! Scheduling and reminders keep our chiropractic office on track, and the billing tools are excellent.",
        image: "/public/images/users/106.jpg",
        name: "Owen F.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "07/18/23",
        text: "The EHR in Magenda is perfect for our physical therapy team. The user-friendly reminders and billing tools make managing our day a breeze.",
        image: "/public/images/users/105.jpg",
        name: "Jessica L.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "07/16/23",
        text: "Our surgery center couldn’t be happier with Magenda. The intuitive scheduling, reminders, and task features make it easy to manage patient care.",
        image: "/public/images/users/104.jpg",
        name: "Phyllis S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "07/15/23",
        text: "Magenda is ideal for a busy office! The organized reminders, tasks, and clock-in feature are lifesavers for our chiropractic practice.",
        image: "/public/images/users/103.jpg",
        name: "Tina K.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "07/14/23",
        text: "Scheduling, reminders, and billing have never been easier for our internal medicine practice. Magenda’s user-friendly interface is fantastic!",
        image: "/public/images/users/102.jpg",
        name: "Dr. Andrew K.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "07/12/23",
        text: "Magenda’s EHR is perfect for physical therapy. The reminders and task integration help us manage patient care efficiently and stay on schedule.",
        image: "/public/images/users/101.jpg",
        name: "Rachel P.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "07/12/23",
        text: "Our chiropractic office loves the easy-to-use scheduling and reminders. The billing tools are efficient, and the clock-in feature is a big bonus!",
        image: "/public/images/users/100.jpg",
        name: "Alicia K.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "07/11/23",
        text: "Magenda has improved our patient flow significantly! The reminders, Dr. calendar, and intuitive design keep everything organized and efficient.",
        image: "/public/images/users/99.jpg",
        name: "Dr. Susan L.",
        speciality: "Internal Medicine",
      },
      {
        rating: "4.5",
        date: "07/07/23",
        text: "Magenda’s EHR is the best we’ve used. The reminders and e faxing is extremely helpful.",
        image: "/public/images/users/98.jpg",
        name: "Dr George F.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "07/05/23",
        text: "The clock-in feature and task integration make Magenda an essential tool for our office. The billing tools are user-friendly and efficient.",
        image: "/public/images/users/97.jpg",
        name: "Erin O.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "07/03/23",
        text: "Our physical therapy office loves the reminders and intuitive EHR. Magenda has made it easier for us to stay organized.",
        image: "/public/images/users/96.jpg",
        name: "Noah P.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "07/01/23",
        text: "Magenda’s EHR is incredibly helpful in our chiropractic practice. The organized scheduling and reminders ensure we never miss a step.",
        image: "/public/images/users/95.jpg",
        name: "Dr. Jason C.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "06/28/23",
        text: "For our surgery center, Magenda has made everything simpler. The reminders, EHR, and billing tools work perfectly for a smooth workflow.",
        image: "/public/images/users/94.jpg",
        name: "Monica G.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "06/24/23",
        text: "Magenda has organized our office! The Dr. calendar and task feature keep us on track, while the billing and collections are excellent.",
        image: "/public/images/users/93.jpg",
        name: "Jack J.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "06/24/23",
        text: "The clock-in feature is a great addition in Magenda. Scheduling and reminders are straightforward, making it ideal for a busy physical therapy practice.",
        image: "/public/images/users/92.jpg",
        name: "Rhonda L.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "06/22/23",
        text: "The intuitive design and scheduling options make Magenda a great fit for our chiropractic office. The reminders keep us organized and on track.",
        image: "/public/images/users/91.jpg",
        name: "Grace P.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "06/20/23",
        text: "Magenda’s clock-in feature is a perfect solution for tracking hours. Scheduling, reminders, and billing have made our internal medicine office run more smoothly.",
        image: "/public/images/users/90.jpg",
        name: "Wendy S.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "06/17/23",
        text: "The reminders, task feature, and organized interface in Magenda make running our office simple. It’s user-friendly and visually appealing too!",
        image: "/public/images/users/89.jpg",
        name: "Dr. Robert T.",
        speciality: "Internal Medicine",
      },
      {
        rating: "4.5",
        date: "06/15/23",
        text: "We’re impressed with Magenda’s EHR for physical therapy. The reminders, Dr. calendar, and organized interface help us manage our day smoothly.",
        image: "/public/images/users/88.jpg",
        name: "June C.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "06/11/23",
        text: "Using Magenda has streamlined our entire surgery center. The beautiful interface, reminders, and billing tools make it easy to manage patient appointments.",
        image: "/public/images/users/87.jpg",
        name: "Debbie B.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "06/09/23",
        text: "Magenda is exactly what our chiropractic practice needed. The reminders and tasks keep us organized, and the clock-in feature is perfect for staff management.",
        image: "/public/images/users/86.jpg",
        name: "Oliver D.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "06/08/23",
        text: "The billing tools are smooth and efficient in Magenda. Scheduling is straightforward, and the reminders keep our physical therapy team on track every day.",
        image: "/public/images/users/85.jpg",
        name: "Clara M.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "06/05/23",
        text: "Magenda’s EHR is fantastic for our internal medicine practice. Scheduling and reminders are flawless, and the user-friendly design makes it easy for everyone on our team.",
        image: "/public/images/users/84.jpg",
        name: "Annette S.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "06/04/23",
        text: "We couldn’t run our chiropractic office without Magenda. The reminders and EHR keep us organized, and the clock-in feature is essential for managing staff time.",
        image: "/public/images/users/83.jpg",
        name: "Samantha F.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "05/30/23",
        text: "Magenda has transformed our surgery center! Scheduling, reminders, and the intuitive interface make patient flow and billing so seamless.",
        image: "/public/images/users/82.jpg",
        name: "Dr. Michael S.",
        speciality: "Surgeon",
      },
      {
        rating: "4.5",
        date: "05/28/23",
        text: "Magenda’s EHR keeps patient records organized, and the scheduling and reminders keep us on track. Great for a busy practice.",
        image: "/public/images/users/81.jpg",
        name: "Kim B.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "05/26/23",
        text: "Magenda’s design is top-notch. The reminders and task features are invaluable for our chiropractic office.",
        image: "/public/images/users/80.jpg",
        name: "Denise M.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "05/25/23",
        text: "Our surgery center loves Magenda! The reminders, billing tools, and EHR make everything simple and efficient.",
        image: "/public/images/users/79.jpg",
        name: "Tamara T.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "05/21/23",
        text: "The organized interface in Magenda is wonderful. We rely on the reminders, billing, and clock-in features daily!",
        image: "/public/images/users/78.jpg",
        name: "Lucas M.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "05/20/23",
        text: "Magenda’s EHR is exactly what we needed. The reminders, scheduling, and Dr. calendar make managing our physical therapy office easy.",
        image: "/public/images/users/77.jpg",
        name: "Steve L.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "05/20/23",
        text: "We couldn’t ask for a better solution! The reminders, billing, and clock-in features in Magenda make our internal medicine practice run smoothly.",
        image: "/public/images/users/76.jpg",
        name: "Joy L.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "05/16/23",
        text: "Our chiropractic office loves how intuitive Magenda is. The task integration and reminders are perfect for keeping us on track.",
        image: "/public/images/users/75.jpg",
        name: "Nicole K.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "05/15/23",
        text: "Magenda’s clock-in feature has simplified our workflow. The reminders and billing tools are so helpful, and the Dr. calendar is incredibly organized.",
        image: "/public/images/users/74.jpg",
        name: "Ruth F.",
        speciality: "Internal Medicine",
      },
      {
        rating: "4.5",
        date: "05/14/23",
        text: "The user-friendly interface and seamless reminders in Magenda make managing our surgery center a breeze. The billing tools are flawless!",
        image: "/public/images/users/73.jpg",
        name: "Judy L.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "05/12/23",
        text: "Magenda is fantastic for our physical therapy office! The intuitive design, reminders, and task feature make it the perfect choice.",
        image: "/public/images/users/72.jpg",
        name: "Daniel W.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "05/11/23",
        text: "Our chiropractic practice loves the easy-to-use EHR. The clock-in feature helps with staff hours, and reminders keep everything organized.",
        image: "/public/images/users/71.jpg",
        name: "Kathy S.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "05/09/23",
        text: "The EHR is excellent for internal medicine. The scheduling, reminders, and billing system in Magenda keep everything running smoothly.",
        image: "/public/images/users/70.jpg",
        name: "Christine L.",
        speciality: "Internal Medicine",
      },
      {
        rating: "4.5",
        date: "05/09/23",
        text: "Magenda has made our surgery center more efficient. The intuitive reminders and billing tools keep us organized, and the clock-in feature helps track hours accurately.",
        image: "/public/images/users/69.jpg",
        name: "Janet P.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "05/07/23",
        text: "Our physical therapy practice relies on Magenda’s reminders and scheduling to keep everything on track. The task feature is a bonus!",
        image: "/public/images/users/68.jpg",
        name: "Elijah D.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "05/06/23",
        text: "The EHR for our chiropractic office is so intuitive. Scheduling and reminders keep us running smoothly, and the clock-in feature is a game-changer.",
        image: "/public/images/users/67.jpg",
        name: "Helen P.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "05/05/23",
        text: "We love Magenda’s design! The task and calendar features help us keep organized, and the billing tools are efficient for collections.",
        image: "/public/images/users/66.jpg",
        name: "Sarah J.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "05/03/23",
        text: "Magenda’s EHR makes patient management easy, and the reminders help us stay on top of appointments. The clock-in feature is a great addition.",
        image: "/public/images/users/65.jpg",
        name: "Rita Y.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "05/03/23",
        text: "Our surgery center couldn’t function without Magenda. The reminders, billing, and task integration keep everything streamlined.",
        image: "/public/images/users/64.jpg",
        name: "Maria O.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "04/30/23",
        text: "The clock-in feature is perfect for managing our staff. The billing tools and reminders make our physical therapy office run seamlessly!",
        image: "/public/images/users/63.jpg",
        name: "Rose M.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "04/28/23",
        text: "With Magenda, our chiropractic office has never been more organized. The reminders, scheduling, and billing tools are all so user-friendly.",
        image: "/public/images/users/62.jpg",
        name: "Dr. Robert M.",
        speciality: "Chiropractor",
      },
      {
        rating: "5.0",
        date: "04/27/23",
        text: "The Dr. calendar and tasks make Magenda ideal for a busy medical office. Our entire team finds it so easy to use!",
        image: "/public/images/users/61.jpg",
        name: "Ashley M.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "04/26/23",
        text: "The EHR in Magenda is exactly what our physical therapy office needed. The reminders, scheduling, and tasks help us stay organized and efficient.",
        image: "/public/images/users/60.jpg",
        name: "Brenda L.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "04/25/23",
        text: "Magenda’s intuitive design makes scheduling and billing effortless. The reminders keep us on top of everything, and the clock-in feature is a huge help.",
        image: "/public/images/users/59.jpg",
        name: "William C.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "04/25/23",
        text: "Our surgery center is thriving with Magenda! The reminders and task feature keep us organized, and the billing and collections are smooth.",
        image: "/public/images/users/58.jpg",
        name: "Dr. Linda F.",
        speciality: "Surgeon",
      },
      {
        rating: "5.0",
        date: "04/24/23",
        text: "The clock-in feature is so efficient for tracking hours. The reminders, scheduling, and billing tools make Magenda essential for our chiropractic practice.",
        image: "/public/images/users/57.jpg",
        name: "Jessica S.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "04/20/23",
        text: "Magenda’s design is sleek and intuitive. The EHR for our physical therapy office is fantastic, and the reminders keep us on schedule every day.",
        image: "/public/images/users/56.jpg",
        name: "Elizabeth P.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "04/18/23",
        text: "Having everything in one place with Magenda is a lifesaver. The reminders, clock-in, and billing tools make our medical office run smoothly.",
        image: "/public/images/users/55.jpg",
        name: "Benjamin M.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "04/17/23",
        text: "Magenda’s EHR and task integration have simplified our workflows. Our physical therapy team loves how user-friendly the entire system is!",
        image: "/public/images/users/54.jpg",
        name: "Lana T.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "04/15/23",
        text: "Our chiropractic office thrives with Magenda! The reminders, scheduling, and clock-in features help us keep everything on track. Couldn’t ask for a better system.",
        image: "/public/images/users/53.jpg",
        name: "John T.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "04/14/23",
        text: "The task feature in Magenda keeps us on top of daily goals. The user-friendly design makes it easy for our entire team to stay organized.",
        image: "/public/images/users/52.jpg",
        name: "Patricia L.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "04/12/23",
        text: "Scheduling, reminders, EHR, and more – Magenda has it all! It’s perfect for our surgery center, especially with the easy billing and task integration.",
        image: "/public/images/users/51.jpg",
        name: "Steve K.",
        speciality: "Surgeon",
      },
      {
        rating: "5.0",
        date: "04/12/23",
        text: "Magenda’s notifications and reminders ensure we never miss an appointment. The EHR and billing tools have transformed our medical office’s efficiency.",
        image: "/public/images/users/50.jpg",
        name: "Pamela J.",
        speciality: "Chiropractor",
      },
      {
        rating: "4.5",
        date: "04/10/23",
        text: "Our team loves the clock-in feature. The scheduling, reminders, and tasks are well-organized, and the billing is straightforward. Highly recommend Magenda!",
        image: "/public/images/users/49.jpg",
        name: "Robert J.",
        speciality: "Coding specialists",
      },
      {
        rating: "5.0",
        date: "04/07/23",
        text: "The interface is beautiful and so user-friendly. The reminders are a must-have, and Magenda’s EHR is an ideal solution for our physical therapy practice.",
        image: "/public/images/users/48.jpg",
        name: "Dr. Sonya W.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "04/05/23",
        text: "Magenda’s billing system and reminders are top-notch for our chiropractic office. The easy-to-navigate EHR keeps patient records organized and accessible.",
        image: "/public/images/users/47.jpg",
        name: "Rachel B.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "04/04/23",
        text: "We’ve saved so much time using Magenda! The scheduling and reminders streamline our day, and the clock-in feature helps us manage staff hours perfectly.",
        image: "/public/images/users/46.jpg",
        name: "Karen A.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "04/02/23",
        text: "The Dr. calendar and task features are so helpful! Our internal medicine office is much more organized with Magenda, and the billing tools are a bonus.",
        image: "/public/images/users/45.jpg",
        name: "Mark F.",
        speciality: "Internal Medicine",
      },
      {
        rating: "5.0",
        date: "04/01/23",
        text: "Magenda keeps everything in one place, making our practice run smoothly. The billing tools are fantastic, and the reminders ensure we stay on track with appointments.",
        image: "/public/images/users/44.jpg",
        name: "Eva B.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "03/30/23",
        text: "Our physical therapy office loves Magenda’s tracking and notification features. The EHR is easy to use, and we rely on it daily for organized patient care.",
        image: "/public/images/users/43.jpg",
        name: "Dr. Robert H.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "03/25/23",
        text: "The clock-in feature is a game-changer in our surgery center! Magenda’s reminders and scheduling help us manage patient flow effortlessly.",
        image: "/public/images/users/42.jpg",
        name: "Lora P.",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "03/22/23",
        text: "Magenda’s intuitive design allows our team to work efficiently. The task integration and EHR make record-keeping a breeze. Highly recommend for medical offices!",
        image: "/public/images/users/41.jpg",
        name: "Emma T.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "03/21/23",
        text: "The beautiful interface of Magenda makes it enjoyable to use. We love the EHR for physical therapy, and the reminders are fantastic for keeping appointments organized.",
        image: "/public/images/users/40.jpg",
        name: "Dr. Jason K.",
        speciality: "Physical Therapist",
      },
      {
        rating: "5.0",
        date: "03/19/23",
        text: "The clock-in feature is incredibly useful in Magenda, along with the streamlined billing and easy scheduling. It’s a great fit for our chiropractic practice.",
        image: "/public/images/users/39.jpg",
        name: "Karen L.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "03/17/23",
        text: "Our surgery center is running smoothly thanks to Magenda’s comprehensive scheduling and task tools. The system is so organized and visually appealing.",
        image: "/public/images/users/38.jpg",
        name: "Rachel G.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "03/15/23",
        text: "We’ve used multiple systems, but Magenda outshines them all! The reminders, scheduling, and intuitive EHR make it so easy to manage a busy medical office.",
        image: "/public/images/users/37.jpg",
        name: "Tom N.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "03/15/23",
        text: "The billing and collections in Magenda are flawless. Our office loves how user-friendly the software is, and the Dr. calendar keeps us on schedule every day!",
        image: "/public/images/users/36.jpg",
        name: "Jessica C.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "03/15/23",
        text: "Magenda’s EHR is perfect for our physical therapy practice. It’s user-friendly and keeps us organized, while reminders and the task feature ensure nothing falls through the cracks.",
        image: "/public/images/users/35.jpg",
        name: "Dr. Linda J.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "03/13/23",
        text: "Our chiropractic team appreciates the flexibility of Magenda’s scheduling and reminders. The clock-in feature is a great tool to track our team’s time.",
        image: "/public/images/users/34.jpg",
        name: "Robert P.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "03/11/23",
        text: "Absolutely love using Magenda for our surgery center. The EHR is so well designed, and the billing and scheduling are simple and effective. We’re saving hours each week.",
        image: "/public/images/users/33.jpg",
        name: "Sarah M.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "03/09/23",
        text: "Magenda has completely streamlined our office! The scheduling and reminders are a lifesaver, and the beautiful, organized interface is intuitive for our entire staff.",
        image: "/public/images/users/32.jpg",
        name: "Dr. Emily B.",
        speciality: "Physical Therapist",
      },
      {
        rating: "4.5",
        date: "03/09/23",
        text: "MagendaMD's scheduling tool is incredibly user-friendly and adaptive to our clinic's needs. The straightforward interface and customizable options have made managing appointments a breeze.",
        image: "/public/images/users/1.jpg",
        name: "Ava M.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "03/08/23",
        text: "The integrated SMS feature is a game-changer for patient communication. The automated reminders and updates have significantly improved appointment adherence, reducing no-shows and enhancing patient engagement.",
        image: "/public/images/users/7.jpg",
        name: "Lily Sullivan",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "03/05/23",
        text: "Transitioning from scheduling to managing appointments within MagendaMD is seamless. The integrated approach provides a comprehensive overview, allowing for easy modifications and efficient tracking.",
        image: "/public/images/users/11.jpg",
        name: "Ethan L.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "03/04/23",
        text: "MagendaMD's task management has brought a new level of organization to our workflow. Centralizing tasks within the EHR system has improved team collaboration and productivity.",
        image: "/public/images/users/8.jpg",
        name: "Nolan Walker",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "02/27/23",
        text: "The calendar feature is visually appealing and functionally robust. It has become our go-to tool for managing daily schedules, offering a clear view of appointments and tasks.",
        image: "/public/images/users/5.jpg",
        name: "Sophia W.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "02/25/23",
        text: "MagendaMD's billing module is efficient and transparent. From invoicing to payment tracking, it seamlessly integrates with other features, contributing to a smoother financial management process.",
        image: "/public/images/users/6.jpg",
        name: "Isla P.",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "02/21/23",
        text: "The secure faxing capability aligns perfectly with our commitment to patient privacy. MagendaMD provides a reliable and confidential platform for exchanging medical documents.",
        image: "/public/images/users/4.jpg",
        name: "Chloe Ross",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "02/18/23",
        text: "The user interface is intuitive, making it easy for our team to navigate and utilize the software effectively. Even staff members with varying tech proficiency find it accessible.",
        image: "/public/images/users/9.jpg",
        name: "Emma H.",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "02/17/23",
        text: "MagendaMD's automation features have streamlined our routine tasks. The system's intelligence in automating processes has freed up valuable time, allowing us to focus more on patient care.",
        image: "/public/images/users/2.jpg",
        name: "Olivia R.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "02/15/23",
        text: "The customer support from MagendaMD has been exceptional. Responsive, knowledgeable, and always ready to assist, they have contributed to a positive experience in using the software.",
        image: "/public/images/users/10.jpg",
        name: "Caleb Simmons",
        speciality: "Coding specialists",
      },
      {
        rating: "5.0",
        date: "02/14/23",
        text: "MagendaMD's scheduling feature is a game-changer! The interface is intuitive, and customization options make it adaptable to our clinic's unique needs. Managing appointments has never been this seamless.",
        image: "/public/images/users/12.jpg",
        name: "Mia C.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "02/11/23",
        text: "The integrated SMS functionality is a standout feature. Automated reminders keep patients informed, reducing no-shows, and enhancing communication. It's a time-saver for both staff and patients.",
        image: "/public/images/users/14.jpg",
        name: "Jenny Lee",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "02/10/23",
        text: "MagendaMD seamlessly integrates appointment management. The transition from scheduling to managing appointments is smooth, providing a centralized view for efficient tracking and modification.",
        image: "/public/images/users/25.jpg",
        name: "Addison F.",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "02/09/23",
        text: "The task management feature is incredibly useful. It keeps our team organized and on track, fostering collaboration. Having tasks integrated within the EHR system has streamlined our workflow.",
        image: "/public/images/users/27.jpg",
        name: "Carter R.",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "02/06/23",
        text: "MagendaMD's calendar is visually appealing and functional. It serves as a comprehensive overview of our daily operations, making it easy to manage appointments and tasks. A must-have for organized practices.",
        image: "/public/images/users/26.jpg",
        name: "Grace Murphy",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "02/06/23",
        text: "The billing module is a reliable tool for financial management. It simplifies invoicing and payment tracking, ensuring accuracy. Our billing processes have become more efficient and transparent.",
        image: "/public/images/users/15.jpg",
        name: "Kathleen Kelly",
        speciality: "Billing specialist",
      },
      {
        rating: "5.0",
        date: "02/05/23",
        text: "The secure faxing capability aligns perfectly with our commitment to patient privacy. MagendaMD provides a reliable and confidential channel for exchanging medical documents, ensuring compliance with regulations.",
        image: "/public/images/users/16.jpg",
        name: "Paul Fernandez",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "01/27/23",
        text: "The user interface is clean and user-friendly. Navigating through different features is intuitive, making it accessible for all staff members regardless of their tech proficiency.",
        image: "/public/images/users/18.jpg",
        name: "Abigail T.",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "01/19/23",
        text: "MagendaMD's automation features are a time-saver. The system intelligently automates repetitive tasks, reducing manual workload and allowing our team to focus on patient care.",
        image: "/public/images/users/19.jpg",
        name: "Scarlett R.",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "01/15/23",
        text: "The customer support team is responsive and helpful. They've addressed our queries promptly, ensuring a positive experience with the software. Knowing that support is readily available is reassuring.",
        image: "/public/images/users/29.jpg",
        name: "Maria Sanches",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "01/11/23",
        text: "MagendaMD's scheduling feature is a lifesaver for our clinic. The ease of use and flexibility in managing appointments have significantly improved our daily workflow. Customization options allow us to tailor schedules to meet our specific needs.",
        image: "/public/images/users/23.jpg",
        name: "Hazel Griffin",
        speciality: "Administrator",
      },
      {
        rating: "5.0",
        date: "01/08/23",
        text: "The integrated SMS feature is a communication game-changer. Automated reminders and updates keep our patients engaged, resulting in fewer missed appointments. It's a simple yet powerful tool for enhancing patient communication.",
        image: "/public/images/users/17.jpg",
        name: "Harper A.",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "12/28/22",
        text: "Transitioning from scheduling to managing appointments within MagendaMD is seamless. The integrated approach provides a holistic view, making it easy to modify and track appointments. Our staff appreciates the efficiency it brings to our practice.",
        image: "/public/images/users/24.jpg",
        name: "Jasmine Turner",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "12/21/22",
        text: "MagendaMD's automation features are a time-saver for our staff. The system intelligently automates routine tasks, freeing up valuable time to focus on patient care. It's a significant efficiency booster for our practice.",
        image: "/public/images/users/22.jpg",
        name: "Kenzo E.",
        speciality: "Office manager",
      },
      {
        rating: "5.0",
        date: "12/16/22",
        text: "The calendar feature is visually appealing and functionally robust. It serves as our practice's central hub, offering a clear and comprehensive overview of appointments and tasks. Navigating daily schedules has never been easier.",
        image: "/public/images/users/21.jpg",
        name: "Zoey M.",
        speciality: "Administrator",
      },
      {
        rating: "4.5",
        date: "12/15/22",
        text: "MagendaMD's task management is a boon for our team. It centralizes tasks, fostering collaboration and organization. The integrated tasks within the EHR system have streamlined our workflow and improved overall efficiency.",
        image: "/public/images/users/20.jpg",
        name: "Aisha Corte",
        speciality: "Office manager",
      },
      {
        rating: "4.5",
        date: "12/11/22",
        text: "MagendaMD's billing module has simplified our financial processes. From generating invoices to tracking payments, it ensures accuracy and transparency. The billing features seamlessly integrate with other aspects of the software, contributing to a cohesive experience.",
        image: "/public/images/users/28.jpg",
        name: "Silvia Rivera",
        speciality: "Billing specialist",
      },
      {
        rating: "4.5",
        date: "12/06/22",
        text: "The secure faxing capability aligns with our commitment to privacy and compliance. MagendaMD provides a reliable channel for faxing medical documents, ensuring sensitive information is exchanged securely.",
        image: "/public/images/users/30.jpg",
        name: "Emma Nelson",
        speciality: "Medical receptionist",
      },
      {
        rating: "5.0",
        date: "12/01/22",
        text: "The user interface is intuitive and user-friendly. Our team, with varying tech expertise, navigates the system effortlessly. MagendaMD's design contributes to a positive user experience and efficient use of the software.",
        image: "/public/images/users/31.jpg",
        name: "Brooke Blake",
        speciality: "Medical receptionist",
      },
      {
        rating: "4.5",
        date: "11/18/22",
        text: "The customer support from MagendaMD is top-notch. Responsive and knowledgeable, the support team has addressed our inquiries promptly. Knowing we have reliable support adds an extra layer of confidence in using the software.",
        image: "/public/images/users/13.jpg",
        name: "Amir R.",
        speciality: "Coding specialist",
      },
    ];

    return `
      ${users
        .map(
          ({ rating, date, text, image, name, speciality }) => `
            <div class="h-auto swiper-slide">
              <div class="testimonials-card">
                <div class="flex justify-between 2xl:mb-2 mb-1">
                  <span class="2xl:text-2xl text-lg">${rating}</span>
                  <span class="2xl:text-base text-sm">${date}</span>
                </div>
                <img
                  src="/public/images/rating${
                    rating === "5.0" ? "5" : "4.5"
                  }.png"
                  alt="Rating"
                  class="2xl:w-[100px] w-[80px] mb-4"
                />
                <p class="2xl:mb-8 mb-4 2xl:text-base text-sm">
                  ${text}
                </p>
                <div class="flex mt-auto">
                  <div class="2xl:w-[60px] w-[50px] me-8">
                    <img
                      src="${image}"
                      alt="User"
                      class="rounded-full"
                    />
                  </div>
                  <div class="flex flex-col justify-between font-medium py-1">
                    <div class="uppercase text-base">${name}</div>
                    <div class="text-blue-main text-base">${speciality}</div>
                  </div>
                </div>
              </div>
            </div>
          `
        )
        .join("")}
    `;
  };
  $("#swiper-wrapper").html(getTestimonials());
});
